### ISSUE TITLE
SchülerView

### ISSUE THREAD

**Issue by TheM3ercy** [HTLGKRLSW22/SYP22LSW#219]
![Image](https://user-images.githubusercontent.com/43909422/215446806-3a514910-a9b8-4bfb-9655-2e57a7f6e9a4.png)

**Comment by TheM3ercy** [comment]
Verbinden von Frontend und Backend

**Comment by MatthiasStadlbauer** [comment]
Es muss beachtet werden welche Kurse der eingeloggte Schüler sehen darf(Michael) anpassen an das neue Datenmodell

**Comment by TheM3ercy** [comment]
Eintragen sollte funktionieren Simon
