### ISSUE TITLE
bei klick auf seitenleiste ist falsches routing

### ISSUE THREAD

**Issue by FantasyplayHD** [HTLGKRLSW22/SYP22LSW#328]

**Comment by FantasyplayHD** [comment]
![Image](https://user-images.githubusercontent.com/65398780/224691887-6f3088bf-eb70-4058-ad7f-8f59809ad6d3.png)

**Comment by MatthiasStadlbauer** [comment]
Neues Routing "courses/view" für alle (Teacher, Student)
