### ISSUE TITLE
Zustande gekommene Kurse Schüler Informieren

### ISSUE THREAD

**Issue by TheM3ercy** [HTLGKRLSW22/SYP22LSW#41]
Zur deadline Kurse eintragen Schauen ob Kurse mindestteilnehmeranzahl erreicht ist wenn ja wird Jeder der Schüler eine Bestätigungsemail gesendet (Methode aufrufen wird später implementiert)

**Comment by lucaskroni** [comment]
Haben wir schon ein Projekt
